### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/fontview#10]
My main mac runs still on macOS 10.10.
fontview does run just fine (if it is started from the build script). But started from Finder, it does show an error message to require 10.11. I didn’t figure out how to set the DEPLOYMENT_TARGET. Could someone do that?

**Comment by brawer** [comment]
Can you try to build from HEAD, and tell if it works now? I’ve tried to fix this, but I’m not sure if it works because I don’t have a Mac with 10.10.

**Comment by schriftgestalt** [comment]
It works. Thanks.
