### ISSUE TITLE
ssxx alternates endup as default letters

### ISSUE THREAD

**Issue by impallari** [googlei18n/fontview#11]
Hi All, 
When using GlyphsApp for exporting variable font that have a few alternate .ssxx glyphs, they end up as the defaults if I preview the font in fontView. Not sure if this is a Glyphs exporting bug, of if it is a fontView bug... so I'm reporting it to both developers.

**Comment by brawer** [comment]
FontView just calls HarfBuzz for shaping, so this sounds like a bug in HarfBuzz. Or in Glyphs.app, as @impallari wrote. @schriftgestalt, have you already looked into this? If not, I can try to find out, but I’d need the font files to reproduce.

**Comment by schriftgestalt** [comment]
@impallari can you send me the font?

**Comment by brawer** [comment]
Has this been resolved?

**Comment by schriftgestalt** [comment]
I didn’t get the font to test this (@impallari, if you did send it, please send it again).

**Comment by brawer** [comment]
Has this been resolved? It would be good to know whether the problem is in Glyphs or in FontView/HarfBuzz.

**Comment by brawer** [comment]
Friendly ping?

**Comment by felipesanches** [comment]
I talked to Pablo right now about this and he mentioned he can't replicate the issue anymore.
