### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by juandelperal** [googlei18n/fontview#12]
running `python2.7 build.py && ./build/FontView.app/Contents/MacOS/fontview` don't work. It says:
`sh: ./src/third_party/gyp/gyp: No such file or directory`

_fontview/src/third_party/gyp_ appears to be an empty folder.
Thanks

**Comment by flomerboy** [comment]
I get the same error message.

**Comment by brawer** [comment]
Did you pass --recursive to git checkout?

**Comment by brawer** [comment]
See [build instructions in README](https://github.com/googlei18n/fontview#building).
