### ISSUE TITLE
marginal Info.plist suggestions 

### ISSUE THREAD

**Issue by zeilen** [googlei18n/fontview#15]
Hi,

Finder now can show Apps in `/Applications` grouped by category. To put FontView into category Graphics & Design, Info.plist needs the following entry:
`<key>LSApplicationCategoryType</key>	<string>public.app-category.graphics-design</string>`

To have an application icon, Info.plist needs this entry:
`<key>CFBundleIconFile</key>	<string>app</string>`
(`Resources/app.icns` will be used)
You may use this icon: https://github.com/zeilen/googlei18n-fontview-App-icon

bye

**Comment by anthrotype** [comment]
very nice!

**Comment by brawer** [comment]
Thank you, @zeilen! I’ve taken the liberty to modify it your icon so it conforms slightly more to Apple’s human interface guidelines. But feel free to change it again if you’d like; simply send a GitHub pull request on [this PNG](https://github.com/googlei18n/fontview/blob/master/src/fontview/mac/app.iconset/icon_512x512%402x.png).
