### ISSUE TITLE
Supported platforms

### ISSUE THREAD

**Issue by svgeesus** [googlei18n/fontview#16]
Would be good to mention "Linux and MacOS X only" in the readme, so people on other platforms know to look elsewhere rather then clone, build, fail.

**Comment by brawer** [comment]
Thanks for the suggestion! I’ve added a note to the README file. Feel free to make a Windows port (or whatever other platform you’re missing); because the program only calls cross-platform libraries, it shouldn’t be very hard to support another platform.

**Comment by alysdexia** [comment]
Should be good to learn how to spell "than".
