### ISSUE TITLE
FontView uses default font widths if HVAR table does not have a width mapping table.

### ISSUE THREAD

**Issue by readroberts** [googlei18n/fontview#17]
FontView uses default font widths if HVAR table does not have a width mapping table.  ttgxvar.c::ft_var_load_hvar() seems to survive loading the table, and reasonably sets face->blend->hvar_table->widthMap.mapCount to 0.

However, tt_hadvance_adjust() at line 807 then does the check:
    if ( gindex >= face->blend->hvar_table->widthMap.mapCount )
    {
      FT_TRACE2(( "gindex %d out of range\n", gindex ));
      error = FT_THROW( Invalid_Argument );
      goto Exit;
    }

The width mapping table is optional in the HVAR table; and the Adobe Type group now has two test fonts which show this issue.

By the way I am not familiar with the gyp build system. What is the simplest way to get a debug build, non-optimized and with all symbols? Debugging the regular build with lldb was a bit challenging. Do I edit 'common.gypi' or edit build.py so that args.release is set to '',  or something else?

**Comment by brawer** [comment]
Thanks for the report; filed [FreeType bug 50170](https://savannah.nongnu.org/bugs/index.php?50170).

Would Adobe contribute a test font (just 1-2 glyphs) to [Unicode’s text rendering tests](https://github.com/unicode-org/text-rendering-tests)? You’d help making sure that this is getting fixed across all OpenType implementations.

**Comment by brawer** [comment]
@readroberts, if you can’t contribute a test font to Unicode, could you send me your font by e-mail so I can try to reproduce? @lemzwerg [wrote on the FreeType bug](https://savannah.nongnu.org/bugs/index.php?50170):

> Please test with the current git of FreeType! I believe this has been fixed already.

**Comment by miguelsousa** [comment]
@brawer I'll work on a test font

**Comment by brawer** [comment]
Added [test case HVAR-1](https://raw.githack.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#HVAR-1) to Unicode text rendering tests. @readroberts, do you want me to cut a new release of FontView, or is it OK to wait until @lemzwerg has cut a new FreeType release?

**Comment by miguelsousa** [comment]
@brawer if a new release of FontView shows the correct advances, it will be helpful to have it available. Thanks.

**Comment by brawer** [comment]
Sure, no problem. I’ve cut fresh releases for fontview and fontdiff, both tagged as v0.2.2. Travis is still working on the release binaries. When they’re fully built, Travis should push ZIP files for downlod to the respective GitHub release pages.
