### ISSUE TITLE
Combining accents

### ISSUE THREAD

**Issue by frankrolf** [googlei18n/fontview#19]
Something unexpected happens when using combining accents: 
Unless the target combination actually exists as a proper code point, such as `U+0061` (a) + `U+0300` (combining grave) = `U+00E0` (agrave), they fall back to .notdef.

The combining accents in question definitely are contained in the font, the sequence used here:
`G̃g̃` or `U+0047 U+0303 U+0067 U+0303`.

The attached screenshot of course is not a direct comparison, it is just a demonstration to show the expected result (both variable and static fonts are built from the same data).

<img width="1440" alt="screen shot 2017-02-01 at 16 53 20" src="https://cloud.githubusercontent.com/assets/2049645/22533232/8916ab4c-e8a1-11e6-9d48-ceda123602d7.png">

**Comment by brawer** [comment]
Can you send me the font? `sascha@brawer.ch`

**Comment by frankrolf** [comment]
That’s done. Curious what you find!

**Comment by brawer** [comment]
Found the problem: Your `cmap` table had no entry for U+0303 and other combining characters. When I dump your font to TTX with fonttools, manually add `<map code="0x303" name="tildecmb"/>` to the `cmap` table, and convert this back to binary OpenType, it works fine.

![image](https://cloud.githubusercontent.com/assets/1527880/22589312/f3fd01ae-ea09-11e6-8173-8653d31c3e8b.png)
