### ISSUE TITLE
Nastaliq looks terrible

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontview#2]
NotoNastaliq looks terribly broken in FontView. Currently, both the horizontal and the vertical offset is getting added to the current x/y position. Instead, the vertical offset should probably be subtracted.

<img width="705" alt="screen shot 2016-08-25 at 12 09 21 pm" src="https://cloud.githubusercontent.com/assets/1527880/17965428/f2052c40-6abc-11e6-939d-4b64a5b55595.png">

**Comment by khaledhosny** [comment]
Looks like you are using the wrong sign for y offsets (moving the in the opposite direction).

**Comment by brawer** [comment]
Indeed, if I subtract the y offset, it fixes the problem:

<img width="1041" alt="screen shot 2016-08-25 at 12 08 08 pm" src="https://cloud.githubusercontent.com/assets/1527880/17965574/958afae8-6abd-11e6-94e6-5d62efb0f3e9.png">

**Comment by khaledhosny** [comment]
Graphics systems tend to differ on how they hand Y coordinates, in some +ve moves up while in others it moves down.
