### ISSUE TITLE
[Build Error] fatal error: 'ucdn.h' file not found

### ISSUE THREAD

**Issue by lgcc** [googlei18n/fontview#20]
After clone the git repo and `cd` into it,  run `python build.py` will stop at

```sh
  CXX(target) out/Default/obj.target/harfbuzz/src/third_party/harfbuzz/harfbuzz/src/hb-ucdn.o
../src/third_party/harfbuzz/harfbuzz/src/hb-ucdn.cc:21:10: fatal error: 'ucdn.h' file not found
#include "ucdn.h"
         ^
1 error generated.
```

Then I use `CPPFLAGS=-I$PWD/src/third_party/harfbuzz/harfbuzz/src/hb-ucdn python build.py` to get over this. Later I stuck at

```sh
make: *** No rule to make target `out/Default/obj.target/ucdn/src/third_party/ucdn/ucdn/ucdn.o', needed by `out/Default/libucdn.a'.  Stop.
```

**Comment by brawer** [comment]
It works on Travis: https://travis-ci.org/googlei18n/fontview

**Comment by lgcc** [comment]
Yeah, you are right. It really works. 

just now I found that I miss a submodule, when I ran `git submodule init` I got

```sh
Submodule 'src/third_party/ucdn/ucdn' (https://github.com/grigorig/ucdn.git) registered for path 'src/third_party/ucdn/ucdn'
```

so I updated submodule and I got  `fontview` build. Sorry for it.

**Comment by brawer** [comment]
No problem. Enjoy the tool, and don’t hesitate to make changes; it’s free software!
