### ISSUE TITLE
Advance width of some variable glyphs does not change

### ISSUE THREAD

**Issue by miguelsousa** [googlei18n/fontview#24]
* [FreeType bug #50678](https://savannah.nongnu.org/bugs/index.php?50678)
* [Test font TestHVARTwo](https://github.com/unicode-org/text-rendering-tests/pull/26)

**Comment by brawer** [comment]
Thanks for the report! I’ve taken your test font (thanks for it!) and added [test case HVAR-2](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#HVAR-2) to the test suite. Also, I’ve cut a fresh release of [FontView (v0.2.3)](https://github.com/googlei18n/fontview/releases/tag/v0.2.3) which fixes this problem.

**Comment by miguelsousa** [comment]
Thank you.
