### ISSUE TITLE
Updating README and build instructions for linux

### ISSUE THREAD

**Issue by HinTak** [googlei18n/fontview#30]
Quite pleasantly surprised that it just builds as is with `python build.py` on fedora 25, after getting hold of wx-config. So just a few coments to the top level README.

- "...if you’d like porting the tool to other platforms than macOS." needs updating to say Linux works as is now.

- there is no need to do `git clone --recursive ...` for linux , only `raqm` and `ucdn` are needed for the build. Fedora provides `libraqm` (and `libraqm-devel`) 0.1.1 which is not recent enough, but that might change eventually. Especially `wxWidgets` is a 320MB object store! Not cloning recursively is a big plus.

- `wxWidgets` is provided by `wxGTK3` (and `wx-config` by `wxGTK3-devel`). 3.0.3 works. I tried also with wxGTK-2.8.12 which does not work - piles of compiler errors.

**Comment by khaledhosny** [comment]
Same here on archlinux, only cloning ucdn and raqm modules is enough. I didn’t even need to do anything special about `wx-config`. Of course the built binary is not statically linked, and one needs a distro with latest harfbuzz and freetype.

**Comment by HinTak** [comment]
For me, it was not obvious that `wx-config` should be found inside the platform's `wxGTK*` packages, since fontview refers to `wxWidgets`. But that was the only tricky part. Also, both `wxGTK3` and `wxGTK2` comes with a `wx-config`, but only the one with gtk3 works. I assume it is just that gtk2 stuff isn't being well-maintained.

**Comment by khaledhosny** [comment]
Should be fixed in #31.

**Comment by HinTak** [comment]
Yes.
