### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by EwonRael** [googlei18n/fontview#35]
I've spent some time trying to get fontview up and running on my linux desktop with no luck. I've looked through some of the prior issues and, correct me if I'm wrong, but it looks like there is currently no linux support? If that's the case maybe the readme shouldn't include installation instructions for linux users.

**Comment by behdad** [comment]
I've definitely built it on Linux, but I agree it wasn't the most trivial :(

**Comment by behdad** [comment]
cc @khaledhosny @anthrotype

**Comment by behdad** [comment]
Here.  If you install wxwidgets (on Ubuntu: sudo apt-get install libwxgtk3.0-dev), harfbuzz, freetype, fribid, and libraqm, then the following command builds it for me:
```
$ g++ *.cpp --std=c++11 `pkg-config --cflags --libs harfbuzz freetype2 fribidi raqm` `wx-config --cflags --libs`
```

**Comment by EwonRael** [comment]
Thanks for the quick response! I've run into another wall, however. The program compiles, but when I try to run it I get the following error message. 

`Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8).
Aborted (core dumped)
`

I've poked around a bit, but this really isn't my area of expertise.

**Comment by khaledhosny** [comment]
After installing the dependencies, `python build.py` should just work. You don’t need most of the sumboldules on Linux, if you fetched them it might be safer to just:
```sh
git submodule deinit --all
git submodule update --init src/third_party/raqm/libraqm
python build.py
```

**Comment by EwonRael** [comment]
There's a big difference between what _should_ work and what _does_ in practice unfortunately. 

`fontview returned non-zero exit status 1`

I can't get past this error, which is why I submitted the original issue report. @behdad 's solution at least gets the program to compile, just can't run it.

**Comment by brawer** [comment]
@khaledhosny, what would it take to support variation fonts in the GNOME font viewer? From glancing over the [code for your Sushi font widget](https://github.com/GNOME/gnome-font-viewer/blob/master/src/sushi-font-widget.c), I guess it would mainly be a matter of adding variations to Pango? I wonder if there’s much point in maintaining FontView for Linux when there’s already an existing font viewer that ships with GNOME. What do you think?

**Comment by behdad** [comment]
> I wonder if there’s much point in maintaining FontView for Linux

We definitely want it for development & testing purposes...

**Comment by behdad** [comment]
> Mismatch between the program and library build versions detected. The library used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8), and your program used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8). Aborted (core dumped)

That's a different issue and not fontview-specific.  Try googling around.  Try using `--std=c++14` instead of `--std=c++11` in the compile line.

**Comment by EwonRael** [comment]
No luck on the `--std=c++14` substitution.

I've done a bit of goggling, but because I'm not much of a code person I haven't had much success.

**Comment by luigiScarso** [comment]
I was able to compile and run fontview  under Ubuntu 16.04 LTS using this script under src/fontview:

    src/fontview# cat do.sh
    
    export PKG_CONFIG_PATH=/opt/fontview/harfbuzz-1.5.0/BUILD/lib/pkgconfig
    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/fontview/freetype-2.8/BUILD/lib/pkgconfig
    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/fontview/fribidi-0.19.7/BUILD/lib/pkgconfig
    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/fontview/raqm-2017-09-02/BUILD/lib/pkgconfig

    #check the paths
    #pkg-config --cflags --libs harfbuzz freetype2 fribidi raqm
    
    #cd  into src/fontview and compile
    g++ *.cpp --std=c++11 `pkg-config --cflags --libs harfbuzz freetype2 fribidi raqm` `wx-config --cflags --libs` -o fontview
    
    strip fontview
    
    ## run it
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/fontview/freetype-2.8/BUILD/lib
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/fontview/raqm-2017-09-02/BUILD/lib
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/fontview/fribidi-0.19.7/BUILD/lib
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/fontview/harfbuzz-1.5.0/BUILD/lib
    
    ./fontview




My wx-config --cflags --libs says 

    # wx-config --cflags --libs
    -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread
    -L/usr/lib/x86_64-linux-gnu -pthread   -lwx_gtk2u_xrc-3.0 -lwx_gtk2u_webview-3.0 -lwx_gtk2u_html-3.0 -lwx_gtk2u_qa-3.0 -lwx_gtk2u_adv-3.0 -lwx_gtk2u_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0 

I have tested it with 
`AdobeVFPrototype.otf` ver 1.003 and latest `Gingham.ttf`, seems all ok.

**Comment by dsmithdewarcom** [comment]
Agreed that the build isn't as trivial as the instructions suggest. On Ubuntu Precise I'm getting "harfbuzz >= 1.4.5 is missing". Upon reading that messing around with harbuzz versions can kill virtualbox, and seeing the fontview src is >500MB, I nuked it. Not ready for prime time. Might need a note to that effect. ;-)

**Comment by anthrotype** [comment]
anybody else noticed a flickering effect when moving the sliders in fontview on Linux?

![out](https://user-images.githubusercontent.com/6939968/32847068-d778612a-ca20-11e7-80f4-e88574e78590.gif)

**Comment by khaledhosny** [comment]
Yes, happens with me all the time.

**Comment by anthrotype** [comment]
any clues?

**Comment by khaledhosny** [comment]
I thought it might be a lack of double buffering, but either wxWidgets had no API to control it or it made no difference, I don’t recall exactly.

**Comment by behdad** [comment]
I have same vague memory as Khaled's.

**Comment by behdad** [comment]
FWIW, I still use the older atm tool instead.

**Comment by adrientetar** [comment]
> I thought it might be a lack of double buffering

gtk is double-buffered by default just like mac, buffering issues generally only happen on win32. Not sure what's going on here.

**Comment by brawer** [comment]
The flickering on Linux was fixed in https://github.com/googlei18n/fontview/commit/d7e7be588d6006535841a155e703d12d0c967abc.
