### ISSUE TITLE
Master does not build on macOS Sierra

### ISSUE THREAD

**Issue by madig** [googlei18n/fontview#37]
See the CI build log: https://travis-ci.org/googlei18n/fontview

**Comment by anthrotype** [comment]
the build error (https://travis-ci.org/googlei18n/fontview/builds/269396516#L390) started appearing since this commit 5 days ago: 058b05e4840366a8ae518f1ff991425fa1fb4a33

the harfbuzz submodule was updated in that commit, maybe some file was moved.

**Comment by anthrotype** [comment]
I think the git submodules were out of sync (forgot to `git submodule update`) and Behdad committed an older version of harfbuzz (maybe also freetype) without noticing.
Let's update all to latest master.

**Comment by anthrotype** [comment]
@madig just pushed https://github.com/googlei18n/fontview/commit/4a8af44a7f079bb9d4740c659ec17b9376d1f4ee

please try to rebuild after a `git pull && git submodule update`

**Comment by madig** [comment]
Works. Thanks!

**Comment by behdad** [comment]
Thanks.  Sorry about that.  The submodules changes were unintended.
