### ISSUE TITLE
Freetype version 19?

### ISSUE THREAD

**Issue by n8willis** [googlei18n/fontview#38]
Trying to build on an Ubuntu 17.04 system (fresh install), build.py throws the curious error 

`freetype2 >= 19.0.13 is missing`

That seems to come from commit dfcf74d ... since Freetype is only at version 2.8.1, is that actually meant to be a check for fribidi?

**Comment by n8willis** [comment]
Forgot to add: assuming that the FreeType dependency is the important one, not fribidi, as the commit message suggests, what is the actual required minimum version?

**Comment by anthrotype** [comment]
oops.. yeah, for freetype should be 2.8.1.

PR?

**Comment by anthrotype** [comment]
@n8willis I applied the change, could you please check if it works now? thanks

**Comment by n8willis** [comment]
It passes the test now, yeah. Still tackling other build issues, though....
Thanks!

**Comment by anthrotype** [comment]
@n8willis I actually reverted that commit so now it's back to 19.0.3. @khaledhosny pointed out that that is the correct libtool version for the freetype library (it corresponds to freetype 2.7.1).
https://github.com/googlei18n/fontview/commit/256821425ae200d7b7d5ae2058f293f98d33b6b3#commitcomment-24846362

**Comment by n8willis** [comment]
OK. I can confirm that it builds, if one is willing to follow the various tips in #35.
