### ISSUE TITLE
Interpolation / kerning errors in variable fonts

### ISSUE THREAD

**Issue by jeremymickel** [googlei18n/fontview#39]
I'm making a 2-axis variable font. I can generate through fontmake without error, but I'm seeing some strange things when I proof in Illustrator / Photoshop 2018.

<img width="613" alt="screen shot 2017-11-09 at 2 42 39 pm" src="https://user-images.githubusercontent.com/2964496/32636939-fc413180-c56b-11e7-9910-4663a8f311cf.png">

There are kerning pairs that have no basis in the masters. In this example **.N** is -50 and **OT** is -110. In the masters these values are both 0.

<img width="1395" alt="screen shot 2017-11-09 at 4 22 56 pm" src="https://user-images.githubusercontent.com/2964496/32636946-0518087e-c56c-11e7-96cf-396aeb6496dd.png">

There are lots of interpolation errors that show up at seemingly random places as you drag through the width and weight options. I don't see the same interpolation errors when I proof in FontView.

I'm attaching my designspace doc for reference (saved as .txt). I'm new to this so I'm sure there are some things wrong, but I wanted to report in case these are actual errors in fontmake.

Thanks in advance!

[CHOP-Variable_ALL.txt](https://github.com/googlei18n/fontview/files/1459644/CHOP-Variable_ALL.txt)

**Comment by anthrotype** [comment]
maybe you meant to open an issue for https://github.com/googlei18n/fontmake?

**Comment by jeremymickel** [comment]
Sorry about that - thanks!
