### ISSUE TITLE
Syntax error in build.py

### ISSUE THREAD

**Issue by LibertyType** [googlei18n/fontview#4]
Down to the last little part and I got this:

server:~ georgethomas2$ cd fontview
server:fontview georgethomas2$ python build.py && ./build/FontView.app/Contents/MacOS/fontview
build.py:85: Warning: 'with' will become a reserved keyword in Python 2.6
  File "build.py", line 85
    with codecs.open('src/fontview/mac/Info.plist', 'r', 'utf-8') as info_file:
              ^
SyntaxError: invalid syntax

**Comment by brawer** [comment]
Which python version do you use?

**Comment by LibertyType** [comment]
2.6 and 2.7 are both in the Python folder in /Library. I assume the 
System uses the latest version.

**Comment by brawer** [comment]
With `python2.7` instead of just `python` it should work. I’m adjusting the README to use that; thanks for noticing, and sorry about the trouble!
