### ISSUE TITLE
Build Errors [MacOS 10.12]

### ISSUE THREAD

**Issue by chriszanf** [googlei18n/fontview#40]
I am getting a lot of build errors but instead of posting them here, I have created a Gist and pasted the build log into it:

https://gist.github.com/chriszanf/0b5d7929825d0ebc34ea82eef0359340

Generally, its a lot of errors stating that various commands are depreciated.

Any assistance would be great!

**Comment by brawer** [comment]
These seem to be all warnings (non-fatal errors) in third-party libraries, correct?

**Comment by anthrotype** [comment]
the last line of your gist

```
-bash: /build/FontView.app/Contents/MacOS/fontview: No such file or directory
```

could it be that you tried to lauch fontview with a `/` at the beginning of the path instead of `./` making it an absolute path instead of relative to the current directory where ./build folder is?

just guessing

**Comment by brawer** [comment]
Hm, can’t reproduce.
