### ISSUE TITLE
Can't build on MacOS 10.10

### ISSUE THREAD

**Issue by justvanrossum** [googlei18n/fontview#41]
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: out/Default/obj.target/harfbuzz/src/third_party/harfbuzz/harfbuzz/src/hb-ot-var.o (No such file or directory)
```

Using `python2.7 build.py`.

**Comment by anthrotype** [comment]
did you clone --recursive right?

**Comment by justvanrossum** [comment]
Originally, yes, but now just git pull. Should I start from scratch?

**Comment by anthrotype** [comment]
ok, with git submodules you have to remember two things:

1) the first time, you do `git clone --recursive ...`; if you forgot and did just `git clone` you can always do `git submodule update --init --recursive`
2) then when you do `git pull` at a later stage, you have to also remember to do `git submodule update` to synchronize the submodules. This is required if the commits you are pulling include also updates to the submodules.

**Comment by justvanrossum** [comment]
`git submodule update` did it, thanks!
