### ISSUE TITLE
New errors after phython2.7 fix

### ISSUE THREAD

**Issue by LibertyType** [googlei18n/fontview#5]
New errors after python2.7 fix

server:~ georgethomas2$ cd fontview
server:fontview georgethomas2$ python2.7 build.py && ./build/FontView.app/Contents/MacOS/fontview
./src/third_party/gyp/pylib/gyp/input.py:888: Warning: 'as' will become a reserved keyword in Python 2.6
Traceback (most recent call last):
  File "./src/third_party/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "./src/third_party/gyp/pylib/gyp/**init**.py", line 8, in <module>
    import gyp.input
  File "./src/third_party/gyp/pylib/gyp/input.py", line 888
    except ImportError as e:
                        ^
SyntaxError: invalid syntax

**Comment by LibertyType** [comment]
I did a couple of tests this morning: if I just type Python in Terminal, it uses 2.5, which I found living in /Library/Frameworks. If I type in Python2.7 then it uses that. Obviously I have an old version installed which gets in the way sometimes.

Your previous fix to the command line should work though.

**Comment by LibertyType** [comment]
I'm closing this issue without resolution because I found the precompiled installer for OS X and it works.

**Comment by brawer** [comment]
Glad you found a solution. Do tell if you run into any problems, I’ll gladly look into it.
