### ISSUE TITLE
any way to correct inter-glyph spacing when GetContentScaleFactor() = 1 ?

### ISSUE THREAD

**Issue by bdon** [googlei18n/fontview#50]
Comparing the output of Chrome and FontView on the same font and size:
https://github.com/adobe-fonts/source-sans-pro/blob/release/OTF/SourceSansPro-Regular.otf
https://fonts.google.com/specimen/Source+Sans+Pro

Screenshot: 
![chromevsfontview](https://user-images.githubusercontent.com/77501/50173227-d14f6e00-02c4-11e9-98cb-df9c630ca68e.png)

Notice the space between u and i in "quick"

My understanding is that this might be because FontView is copying the pixels directly to the wxBitmap while Chrome is using Skia and can draw a glyph at a subpixel position - is this correct? If so, is there any way to compensate for this in FreeType? adding FT_LOAD_FORCE_AUTOHINT does not seem to help.

 (EDIT: this only appears when GetContentScaleFactor is 1, a non-retina display. It looks fine on my Macbook retina display.)

**Comment by brawer** [comment]
Indeed! Do you want to give it a try? Pull requests welcome. (Personally, I’ve decided to retire from Google, and right now I’m pursuing other interests...) The FreeType documentation has pseudo code in the note about `lsb_delta` and `rsb_delta` in the [section about FT_GlyphSlotRec](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_GlyphSlotRec); hope this helps.

**Comment by bdon** [comment]
Thanks for those pointers. This is what I attempted https://github.com/bdon/fontview/commit/bad9d1889442a13f6c28ecb106bcaec46223d1e0

following this example: http://git.savannah.gnu.org/cgit/freetype/freetype2-demos.git/tree/src/ftcommon.c#n1407 

It does not result in a noticeable improvement however, in fact it seems to introduce more spacing problems on the above font/size ... am I on the right track here?

**Comment by bdon** [comment]
Note: I am noticing that the freetype2-demos [`ftstring` utility](http://git.savannah.gnu.org/cgit/freetype/freetype2-demos.git/tree/src/ftview.c) looks great (screenshot attached) with the given font/text size. Trying to track down what it does differently than FontView
![screen shot 2018-12-19 at 5 21 27 pm](https://user-images.githubusercontent.com/77501/50251713-c5da7080-03b2-11e9-842d-afb239a2c2dc.png)

**Comment by brawer** [comment]
Thanks for looking into this! Does hb-view (from HarfBuzz) have the same problem? If hb-view renders your font fine, it might be helpful to look into what hb-view (or Cairo, which hb-view calls to render its output) does about sub-pixel positioning. There's a SUBPIXEL_BITS in [hb_view.cc](https://github.com/harfbuzz/harfbuzz/blob/master/util/hb-view.cc).

**Comment by bdon** [comment]
hb-view looks good:
`./hb-view -O png -o hbviewoutput.png --font-size=24 SourceSansPro-Regular.otf "The quick brown fox jumps over the lazy dog."`

![hbviewoutput](https://user-images.githubusercontent.com/77501/50317952-605ab280-048c-11e9-9db5-43943832dbf7.png)

**Comment by bdon** [comment]
I think this is not subpixel related, but because glyph positions are being implicitly truncated instead of rounded when passed to wxWidgets `dc.drawBitmap` 

The HarfBuzz `hb-view` utility renders the text without problems, and calls `cairo_show_text_glyphs` which I think must round decimal positions to the nearest integer: https://github.com/harfbuzz/harfbuzz/blob/master/util/view-cairo.cc#L121

We can emulate the behavior of FontView by flooring the glyph positions with this patch:
```
diff --git a/util/helper-cairo.cc b/util/helper-cairo.cc
index b4f94a98..eb0cf16e 100644
--- a/util/helper-cairo.cc
+++ b/util/helper-cairo.cc
@@ -508,8 +508,8 @@ helper_cairo_line_from_buffer (helper_cairo_line_t *l,
   for (i = 0; i < (int) l->num_glyphs; i++)
   {
     l->glyphs[i].index = hb_glyph[i].codepoint;
-    l->glyphs[i].x = scalbn ((double)  hb_position->x_offset + x, scale_bits);
-    l->glyphs[i].y = scalbn ((double) -hb_position->y_offset + y, scale_bits);
+    l->glyphs[i].x = floor(scalbn ((double)  hb_position->x_offset + x, scale_bits));
+    l->glyphs[i].y = floor(scalbn ((double) -hb_position->y_offset + y, scale_bits));
     x +=  hb_position->x_advance;
     y += -hb_position->y_advance;
 ```
The result is erroneous in the same way as linked above:
![hbviewoutput-floor](https://user-images.githubusercontent.com/77501/50318947-7b302580-0492-11e9-9423-eb06aa573983.png)

In the case of the FreeType `ftstring`, it rounds advances to the nearest 16.16 integer at layout time:
http://git.savannah.gnu.org/cgit/freetype/freetype2-demos.git/tree/src/ftcommon.c#n1039
