### ISSUE TITLE
version missing in info.plist

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/fontview#6]
I’m not sure if I did something wrong or not but after updating to the latest code and rebuilding, the info.plist is missing the version numbers.

**Comment by brawer** [comment]
I’ve set up Travis to watch GitHub for release tags. When a new release gets pushed to GitHub, Travis notices this, automatically builds a release binary for FontView, and deploys it to the GitHub [release page](https://github.com/googlei18n/fontview/releases). It works like this: In [.travis.yml](https://github.com/googlei18n/fontview/blob/master/.travis.yml#L24), Travis is configured to pass the value of the `TRAVIS_TAG` environment variable to the build script. If the `--release` command-line argument is not empty, the build script uses this value for [setting the version in Info.plist](https://github.com/googlei18n/fontview/blob/master/build.py#L81).

**Comment by schriftgestalt** [comment]
The versions number is still missing. The file `FontView.app/Contents/info.plist` should contain this:
```
<key>LSMinimumSystemVersion</key>
<string>10.10</string>
```

**Comment by schriftgestalt** [comment]
and 
```
    <key>CFBundleVersion</key>
    <string></string>
    <key>CFBundleShortVersionString</key>
    <string></string>
```
Should also contain values. This is more cosmetic for users.

**Comment by brawer** [comment]
Thanks for the explanation, much appreciated! Added the `LSMinimumSystemVersion`.

Regarding the other properties: If you compile with `python2.7 build.py --release=1234`, the properties `CFBundleVersion` and `CFBundleShortVersionString` will be set to `1234` inside `Info.plist`. When Travis creates a release binary, it passes the git release tag number to the build script.
