### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nmassi** [googlei18n/fontview#7]
I got this when trying to build 

make: **\* No rule to make target `out/Default/obj.target/core/src/third_party/wxWidgets/wxWidgets/src/common/accelcmn.o', needed by`out/Default/libcore.a'.  Stop.

any ideas why?

**Comment by brawer** [comment]
Have you passed `--recursive` to `git clone`?

**Comment by nmassi** [comment]
Yes, copy, paste from README.md
