### ISSUE TITLE
Letterspacing discrepancies with fonts generated with fontTools varLib

### ISSUE THREAD

**Issue by djrrb** [googlei18n/fontview#9]
I love using this app to test variable fonts. Thank you!

I've noticed that when testing variable fonts that I've made myself, something odd seems to happen with the letterspacing. It could be due to an issue with my build process, but since the spacing seems okay elsewhere, I figured I'd report it in case it is helpful.

Attached is an example GX font, and a screenshot showing FontView, the corresponding source UFO in RoboFont, and the variable font used in the latest Safari nightly build. 

Thanks so much!

[VeriSarif-GX.ttf.zip](https://github.com/googlei18n/fontview/files/524838/VeriSarif-GX.ttf.zip)

<img width="1047" alt="screen shot 2016-10-12 at 10 40 14 am" src="https://cloud.githubusercontent.com/assets/6578861/19314546/84f3c0b8-9068-11e6-9031-192482e355d8.png">

**Comment by brawer** [comment]
Thanks for the report; interesting! What’s your workflow from UFO to binary font file? How did you generate this font, in particular the HVAR table?

**Comment by behdad** [comment]
Right.  There seems to be a problem either with HVAR I generate, or the way FreeType interprets it.  I haven't debugged yet. I'll disable HVAR generate code in varLib for now.

**Comment by behdad** [comment]
https://github.com/fonttools/fonttools/issues/705

**Comment by behdad** [comment]
Please rebuild your font with tip of fonttools.

**Comment by djrrb** [comment]
Thank you! And @brawer, just to confirm, I did use `fontmake -o interpolatable` to build the fonts and `fontTools/varLib/__init__.py` on the designspace to make the variable font and hvar table. I will try rebuilding with the latest.

**Comment by brawer** [comment]
OK, thanks for telling. After stripping the HVAR table away, FontView (respectively HarfBuzz and FreeType, which is what FontView calls internally) has no trouble displaying your font. With CFF2 fonts, FreeType’s HVAR code works fine, but perhaps FreeType has a problem with HVAR in TrueType fonts. Or the problem is in fontmake/fonttools/varLib. As behdad said, we’ll need to figure it out.
